<a href="https://colab.research.google.com/github/arshya-garg/ISTE-Web-Dev-SMP/blob/main/NumPy_for_Data_Analytics_(ISTE_Data_Analytics_SMP'22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Markdown basics

##Heading


```
#Text (No. of '#' used indicates heading levels h1 to h6)
```


*italics*


```
*Text*
```


**b o l d**


```
**Text**
```



#2.   Creating NumPy arrays



In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3], np.int8)
arr

array([1, 2, 3], dtype=int8)

In [ ]:
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats, values will be 'upcasted'

B = np.array([[1, 2.4 + 1.4j, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print("A: ", A, "\nB:  ",  B)


A:  [[1.1 2.  3. ]
 [3.  4.  5. ]] 
B:   [[1. +0.j  2.4+1.4j 3. +0.j ]
 [3. +0.j  4. +0.j  5. +0.j ]]


In [ ]:
c = np.zeros( (2,4) )   # np.ones() as well
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr2 = np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

In [ ]:
ls = np.linspace(1,11,3)
ls

array([ 1.,  6., 11.])

In [ ]:
matrix = np.empty(shape=(2,5), dtype= np.int8)
print(matrix)
help(np.empty)    # Python function

[[-48 -17  50   1   0]
 [  0   0   0   0   0]]
Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
 

In [ ]:
matrix2 = np.empty_like(matrix)
matrix2

array([[-32, -17,  50,   1,   0],
       [  0,   0,   0,   0,   0]], dtype=int8)

In [ ]:
i_matrix = np.identity(4)
i_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
matrix.shape  #Returns a tuple

(2, 5)

In [ ]:
matrix.size

10

In [ ]:
c.dtype

dtype('float64')

In [ ]:
A = A.reshape(3,2)    # m*n must be same
A

array([[1.1, 2. ],
       [3. , 3. ],
       [4. , 5. ]])

In [ ]:
A = A.ravel()   # A.ravel() without assignment?
A.shape

(6,)

#3. Some methods and attributes

In [ ]:
x = [[10,2], [3,4], [5,6]]
arr_x = np.array(x)
arr_x

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

###3.1. Attributes

In [ ]:
arr_x.T

array([[10,  3,  5],
       [ 2,  4,  6]])

In [ ]:
arr_x.flat

In [ ]:
for i in arr_x.flat:
  print(i)

10
2
3
4
5
6


In [ ]:
arr_x.ndim    # Dimensions of array

2

In [ ]:
arr_x.nbytes

48

###3.2. Methods

In [ ]:
print(arr_x.sum())
arr_x.sum(axis=0)

30


array([18, 12])

In [ ]:
A.argmax()    # argmin(), both return indices

5

In [ ]:
A.argsort()   # Also returns array of indices

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr_x.argmax()

0

In [ ]:
arr_x.argmin(axis=0)

array([1, 0])

In [ ]:
arr_x.argsort(axis=1)   # Sorts based on axis

array([[1, 0],
       [0, 1],
       [0, 1]])

#4. NumPy Arrays vs Lists

In [ ]:
[10, 20] + [1, 2]

[10, 20, 1, 2]

In [ ]:
a1 = np.array([10, 20])
a2 = np.array([1,2])
a1+a2     # List-style appending can be done using vstack() / hstack()

array([11, 22])

In [ ]:
a1*a2   # Element-wise multiplication

array([10, 40])

In [ ]:
print(np.sqrt(a2))    # std() gives standard deviation
print(np.max(A))
print(np.min(A))
print(np.sum(A))
print(A)

[1.         1.41421356]
5.0
1.1
18.1
[1.1 2.  3.  3.  4.  5. ]


In [ ]:
B

array([[1. +0.j , 2.4+1.4j, 3. +0.j ],
       [3. +0.j , 4. +0.j , 5. +0.j ]])

In [ ]:
np.where(B>=3)   # Returns tuple; check with type() function

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [ ]:
np.count_nonzero(arr_x)

6

In [ ]:
np.nonzero(arr_x)   # Gives indices in two separate arrays (for each axis)

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 0, 1, 0, 1]))

###4.1. Comparing storage

In [ ]:
import sys  # Library which provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter

In [ ]:
p_array = [1,2,3,4,5]
n_array = np.array(p_array)
print(p_array)
print(n_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
sys.getsizeof(1) * len(p_array)   #getsizeof() takes element index as argument

140

In [ ]:
n_array.itemsize * n_array.size

40

# 5. Slicing

In [ ]:
n_array.tolist()    # Method to return a Python list

[1, 2, 3, 4, 5]

In [ ]:
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A[:2, :4], "\n")  # two rows, four columns

print(A[:1,], "\n")  # first row, all columns

print(A[:,2], "\n")  # all rows, second column

print(A[:, 2:5], "\n")  # all rows, third to the fifth column

print(A[::-1])

[[ 1  4  5 12]
 [-5  8  9  0]] 

[[ 1  4  5 12 14]] 

[ 5  9 11] 

[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]] 

[[-6  7 11 19 21]
 [-5  8  9  0 17]
 [ 1  4  5 12 14]]


# 6. Renaming

In [ ]:
import pandas as pd

# Define a dictionary containing organ donor data 
data= {'Name':['Somya', 'Aditya', 'Pratham', 'Raj'], 
        'Age':[20, 19, 22, 18], 
       'Organ Donor':['Yes', 'No', 'No', 'Yes'],
       'Blood Group':['AB+', 'O+', 'AB+', 'AB-']} 

# Convert the dictionary into DataFrame         
df = pd.DataFrame(data, index = [0,1,2,3])

# Display dataframe (without any change)
print(df,'\n')

# Change all column names
df.columns = ['First Name','Biological Age', 'Donor', 'BG']
print(df,'\n')


      Name  Age Organ Donor Blood Group
0    Somya   20         Yes         AB+
1   Aditya   19          No          O+
2  Pratham   22          No         AB+
3      Raj   18         Yes         AB- 

  First Name  Biological Age Donor   BG
0      Somya              20   Yes  AB+
1     Aditya              19    No   O+
2    Pratham              22    No  AB+
3        Raj              18   Yes  AB- 

